/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as administrativeRoles from "./AdministrativeRoles";
export type { administrativeRoles };
import type * as componentSol from "./Component.sol";
export type { componentSol };
import type * as genericLargeResponseSol from "./GenericLargeResponse.sol";
export type { genericLargeResponseSol };
import type * as mediatorPattern from "./MediatorPattern";
export type { mediatorPattern };
import type * as nonAdministrativeRoles from "./NonAdministrativeRoles";
export type { nonAdministrativeRoles };
export type { APIConsumer } from "./APIConsumer";
export type { ERC20 } from "./ERC20";
export type { ERC725 } from "./ERC725";
export type { FNFToken } from "./FNFToken";
export type { Fractional } from "./Fractional";
export type { FractionalNFT } from "./FractionalNFT";
export type { IERC20 } from "./IERC20";
export type { Migrations } from "./Migrations";
export type { MockOracle } from "./MockOracle";
export type { MockOracleClient } from "./MockOracleClient";
export type { Resource } from "./Resource";
export type { TestContract } from "./TestContract";
