/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OraclizeAddrResolverI } from "./OraclizeAddrResolverI";
export type { OraclizeI } from "./OraclizeI";
export type { SolcChecker } from "./SolcChecker";
export type { UsingOraclize } from "./UsingOraclize";
