/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface TransporterInterface extends utils.Interface {
  functions: {
    "getContractAddress()": FunctionFragment;
    "getName()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "setName(string)": FunctionFragment;
    "shipInventory(uint256)": FunctionFragment;
    "updateInventoryRecord(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getContractAddress"
      | "getName"
      | "onERC721Received"
      | "setName"
      | "shipInventory"
      | "updateInventoryRecord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "shipInventory",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInventoryRecord",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shipInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInventoryRecord",
    data: BytesLike
  ): Result;

  events: {
    "DeliverInventory()": EventFragment;
    "InventRecordUpdated(string,string,uint256)": EventFragment;
    "ItemPacked(uint256)": EventFragment;
    "ItemShipped(string,string,uint256)": EventFragment;
    "UpdateStorageReport()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeliverInventory"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InventRecordUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ItemPacked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ItemShipped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateStorageReport"): EventFragment;
}

export interface DeliverInventoryEventObject {}
export type DeliverInventoryEvent = TypedEvent<[], DeliverInventoryEventObject>;

export type DeliverInventoryEventFilter =
  TypedEventFilter<DeliverInventoryEvent>;

export interface InventRecordUpdatedEventObject {
  phase: string;
  message: string;
  id: BigNumber;
}
export type InventRecordUpdatedEvent = TypedEvent<
  [string, string, BigNumber],
  InventRecordUpdatedEventObject
>;

export type InventRecordUpdatedEventFilter =
  TypedEventFilter<InventRecordUpdatedEvent>;

export interface ItemPackedEventObject {
  id: BigNumber;
}
export type ItemPackedEvent = TypedEvent<[BigNumber], ItemPackedEventObject>;

export type ItemPackedEventFilter = TypedEventFilter<ItemPackedEvent>;

export interface ItemShippedEventObject {
  phase: string;
  message: string;
  id: BigNumber;
}
export type ItemShippedEvent = TypedEvent<
  [string, string, BigNumber],
  ItemShippedEventObject
>;

export type ItemShippedEventFilter = TypedEventFilter<ItemShippedEvent>;

export interface UpdateStorageReportEventObject {}
export type UpdateStorageReportEvent = TypedEvent<
  [],
  UpdateStorageReportEventObject
>;

export type UpdateStorageReportEventFilter =
  TypedEventFilter<UpdateStorageReportEvent>;

export interface Transporter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TransporterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getContractAddress(overrides?: CallOverrides): Promise<[string]>;

    getName(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setName(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    shipInventory(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getContractAddress(overrides?: CallOverrides): Promise<string>;

  getName(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setName(
    name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  shipInventory(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateInventoryRecord(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getContractAddress(overrides?: CallOverrides): Promise<string>;

    getName(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setName(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    shipInventory(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DeliverInventory()"(): DeliverInventoryEventFilter;
    DeliverInventory(): DeliverInventoryEventFilter;

    "InventRecordUpdated(string,string,uint256)"(
      phase?: null,
      message?: null,
      id?: null
    ): InventRecordUpdatedEventFilter;
    InventRecordUpdated(
      phase?: null,
      message?: null,
      id?: null
    ): InventRecordUpdatedEventFilter;

    "ItemPacked(uint256)"(id?: null): ItemPackedEventFilter;
    ItemPacked(id?: null): ItemPackedEventFilter;

    "ItemShipped(string,string,uint256)"(
      phase?: null,
      message?: null,
      id?: null
    ): ItemShippedEventFilter;
    ItemShipped(
      phase?: null,
      message?: null,
      id?: null
    ): ItemShippedEventFilter;

    "UpdateStorageReport()"(): UpdateStorageReportEventFilter;
    UpdateStorageReport(): UpdateStorageReportEventFilter;
  };

  estimateGas: {
    getContractAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setName(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    shipInventory(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getContractAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setName(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    shipInventory(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
