/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ComponentCore__factory } from "./ComponentCore__factory";
export { ComponentRole__factory } from "./ComponentRole__factory";
export { HelperContract__factory } from "./HelperContract__factory";
export { IComponent__factory } from "./IComponent__factory";
export { MainContract__factory } from "./MainContract__factory";
