/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mediatorPatternSol from "./MediatorPattern.sol";
export type { mediatorPatternSol };
import type * as nonAdminRoles from "./NonAdminRoles";
export type { nonAdminRoles };
import type * as mEmployeeRoleSol from "./mEmployeeRole.sol";
export type { mEmployeeRoleSol };
