/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IReceiverInterface extends utils.Interface {
  functions: {
    "approveAppointment()": FunctionFragment;
    "generateReciept(string,uint256,uint256,address,address,address)": FunctionFragment;
    "getRoleName()": FunctionFragment;
    "receiveItems(string,uint256)": FunctionFragment;
    "updateInventoryRecord(uint256)": FunctionFragment;
    "updateReciept(uint256,uint256,uint256,address,address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "approveAppointment"
      | "generateReciept"
      | "getRoleName"
      | "receiveItems"
      | "updateInventoryRecord"
      | "updateReciept"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveAppointment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateReciept",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveItems",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInventoryRecord",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReciept",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateReciept",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInventoryRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReciept",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveAppointment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    generateReciept(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getRoleName(overrides?: CallOverrides): Promise<[string]>;

    receiveItems(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateReciept(
      asset_id: PromiseOrValue<BigNumberish>,
      resource_id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      issuer: PromiseOrValue<string>,
      verifier: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  approveAppointment(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  generateReciept(
    asset_name: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    tokenUri: PromiseOrValue<BigNumberish>,
    verifier: PromiseOrValue<string>,
    issuer: PromiseOrValue<string>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getRoleName(overrides?: CallOverrides): Promise<string>;

  receiveItems(
    asset_name: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateInventoryRecord(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateReciept(
    asset_id: PromiseOrValue<BigNumberish>,
    resource_id: PromiseOrValue<BigNumberish>,
    tokenUri: PromiseOrValue<BigNumberish>,
    issuer: PromiseOrValue<string>,
    verifier: PromiseOrValue<string>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveAppointment(overrides?: CallOverrides): Promise<void>;

    generateReciept(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getRoleName(overrides?: CallOverrides): Promise<string>;

    receiveItems(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateReciept(
      asset_id: PromiseOrValue<BigNumberish>,
      resource_id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      issuer: PromiseOrValue<string>,
      verifier: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveAppointment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    generateReciept(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getRoleName(overrides?: CallOverrides): Promise<BigNumber>;

    receiveItems(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateReciept(
      asset_id: PromiseOrValue<BigNumberish>,
      resource_id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      issuer: PromiseOrValue<string>,
      verifier: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveAppointment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    generateReciept(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getRoleName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveItems(
      asset_name: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateInventoryRecord(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateReciept(
      asset_id: PromiseOrValue<BigNumberish>,
      resource_id: PromiseOrValue<BigNumberish>,
      tokenUri: PromiseOrValue<BigNumberish>,
      issuer: PromiseOrValue<string>,
      verifier: PromiseOrValue<string>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
