/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mAuditorSol from "./mAuditor.sol";
export type { mAuditorSol };
import type * as mManagerSol from "./mManager.sol";
export type { mManagerSol };
import type * as mPickerSol from "./mPicker.sol";
export type { mPickerSol };
import type * as mPutawaySol from "./mPutaway.sol";
export type { mPutawaySol };
import type * as mReceiverSol from "./mReceiver.sol";
export type { mReceiverSol };
import type * as mSupplierSol from "./mSupplier.sol";
export type { mSupplierSol };
import type * as mTransporterSol from "./mTransporter.sol";
export type { mTransporterSol };
