/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPutaway__factory } from "./IPutaway__factory";
export { Putaway__factory } from "./Putaway__factory";
