/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IPutawayInterface extends utils.Interface {
  functions: {
    "addItemStorage(uint256,address,address)": FunctionFragment;
    "getContractAddress()": FunctionFragment;
    "getStorageLocation()": FunctionFragment;
    "putawayInventory(uint256,address,address)": FunctionFragment;
    "updateStorageReport(uint256,address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addItemStorage"
      | "getContractAddress"
      | "getStorageLocation"
      | "putawayInventory"
      | "updateStorageReport"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addItemStorage",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageLocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "putawayInventory",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStorageReport",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addItemStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "putawayInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStorageReport",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPutaway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPutawayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addItemStorage(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getContractAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getStorageLocation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    putawayInventory(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateStorageReport(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addItemStorage(
    AssetId: PromiseOrValue<BigNumberish>,
    verifier: PromiseOrValue<string>,
    issuer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getContractAddress(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getStorageLocation(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  putawayInventory(
    AssetId: PromiseOrValue<BigNumberish>,
    verifier: PromiseOrValue<string>,
    issuer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateStorageReport(
    AssetId: PromiseOrValue<BigNumberish>,
    verifier: PromiseOrValue<string>,
    issuer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addItemStorage(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getContractAddress(overrides?: CallOverrides): Promise<string>;

    getStorageLocation(overrides?: CallOverrides): Promise<BigNumber>;

    putawayInventory(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    updateStorageReport(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addItemStorage(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getContractAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getStorageLocation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    putawayInventory(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateStorageReport(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addItemStorage(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getContractAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getStorageLocation(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    putawayInventory(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateStorageReport(
      AssetId: PromiseOrValue<BigNumberish>,
      verifier: PromiseOrValue<string>,
      issuer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
