/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OraclizeAddrResolverI,
  OraclizeAddrResolverIInterface,
} from "../../../contracts/oraclizeAPI.sol/OraclizeAddrResolverI";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "getAddress",
    outputs: [
      {
        name: "_address",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class OraclizeAddrResolverI__factory {
  static readonly abi = _abi;
  static createInterface(): OraclizeAddrResolverIInterface {
    return new utils.Interface(_abi) as OraclizeAddrResolverIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OraclizeAddrResolverI {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OraclizeAddrResolverI;
  }
}
