/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SolcChecker,
  SolcCheckerInterface,
} from "../../../contracts/oraclizeAPI.sol/SolcChecker";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "x",
        type: "bytes",
      },
    ],
    name: "f",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SolcChecker__factory {
  static readonly abi = _abi;
  static createInterface(): SolcCheckerInterface {
    return new utils.Interface(_abi) as SolcCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SolcChecker {
    return new Contract(address, _abi, signerOrProvider) as SolcChecker;
  }
}
