/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  HelperContract,
  HelperContractInterface,
} from "../../../contracts/Component.sol/HelperContract";

const _abi = [
  {
    inputs: [],
    name: "foo",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607780601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c298557814602d575b600080fd5b600060405190815260200160405180910390f3fea2646970667358221220b906207412d66d5676b6173cbdf9a62d68de755379b18bb5776a273dee6cfe6d64736f6c63430008070033";

type HelperContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HelperContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HelperContract__factory extends ContractFactory {
  constructor(...args: HelperContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<HelperContract> {
    return super.deploy(overrides || {}) as Promise<HelperContract>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): HelperContract {
    return super.attach(address) as HelperContract;
  }
  override connect(signer: Signer): HelperContract__factory {
    return super.connect(signer) as HelperContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HelperContractInterface {
    return new utils.Interface(_abi) as HelperContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HelperContract {
    return new Contract(address, _abi, signerOrProvider) as HelperContract;
  }
}
