/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainlinkRequestInterface } from "./ChainlinkRequestInterface";
export type { LinkTokenInterface } from "./LinkTokenInterface";
