/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAuditor,
  IAuditorInterface,
} from "../../../../../contracts/MediatorPattern/NonAdminRoles/mAuditor.sol/IAuditor";

const _abi = [
  {
    inputs: [],
    name: "createInspectionReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deleteInspectionReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "inspectInventory",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "Id",
        type: "uint256",
      },
    ],
    name: "updateInspectionReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuditor__factory {
  static readonly abi = _abi;
  static createInterface(): IAuditorInterface {
    return new utils.Interface(_abi) as IAuditorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuditor {
    return new Contract(address, _abi, signerOrProvider) as IAuditor;
  }
}
