/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComponentCore } from "./ComponentCore";
export type { ComponentRole } from "./ComponentRole";
export type { HelperContract } from "./HelperContract";
export type { IComponent } from "./IComponent";
export type { MainContract } from "./MainContract";
